### PR TITLE
docs: add a note to show how to upgrade ojs core library

### PR DESCRIPTION
**Pull request by mcanouil**
This PR adds a note on how to upgrade an Observable core library such as Plot.

This is because of recurring questions on this aspect:
- https://github.com/quarto-dev/quarto-cli/discussions/3677
- https://github.com/quarto-dev/quarto-cli/discussions/6410

### CODE REVIEW

**Comment by mcfrank** [comment]
+1! 

Just a quick note that this would be very helpful - right now it's a bit frustrating for users that there's no documentation about how to update observable or even how to see the current install.

**Comment by cscheid** [comment]
I missed this PR earlier. It's a good idea, but let me make a slightly different change instead.

**Comment by cscheid** [comment]
See https://github.com/quarto-dev/quarto-web/commit/0a9728ffb4b103eb1c5843a9939cca7c36760c13

**Comment by mcfrank** [comment]
thank you!

**Pull request closed without merging**
