### PR TITLE
Add a small how-to on how to add a bootstrap button

### PR DESCRIPTION
**Pull request by aborruso**

### CODE REVIEW

**Comment by cscheid** [comment]
I'm just going to register a preference towards not encouraging this kind of thing in our main docs. I'd rather we focus our efforts in documenting quarto features, and not bootstrap features.

**Comment by aborruso** [comment]
A small addition @cderv : I suggest not to add a guide on bootstrap, but how to add a well formatted button in a quarto based site

**Comment by cwickham** [comment]
I agree with @cscheid's sentiment that:
>  we focus our efforts in documenting quarto features, and not bootstrap features.

But I do think we could provide more guidance for users on what HTML output using Bootstrap means for a user. For instance, as in this example, it means you can use existing Bootstrap classes to get nicely formatted elements. 

I'm going to close this, but add it as another example of what we might include in when we rework the HTML Theming docs: https://github.com/quarto-dev/quarto-cli/issues/8654

**Pull request closed without merging**
