### PR TITLE
Blog post for 1.3 release

### PR DESCRIPTION
**Pull request by cwickham**
Rough draft for release blog post, preview at: https://deploy-preview-714--mystifying-jepsen-fa4396.netlify.app/docs/blog/posts/2023-04-26-1.3-release/

To fix once 1.3 is released:
* [x] Add actual link to Release Notes 
* [x] Get an updated list of contributors

### CODE REVIEW

**Comment by jjallaire** [comment]
I think we should bring in a paragraph or two + some screenshots about each of the features into the main post. I also think that we should tweet this post on our main social media channels

**Comment by cwickham** [comment]
@jjallaire I added a custom listing that brings in title, subtitle and image. See in [preview](https://deploy-preview-714--mystifying-jepsen-fa4396.netlify.app/docs/blog/posts/2023-04-26-1.3-release/).
Do you think that is enough, or would some custom copy be more appropriate?

**Comment by jjallaire** [comment]
I think we should use a heading rather than a bullet item for each and have a bit more text than the short pithy summaries (maybe 1 or 2 sentences from the docs?). I also think there should be link to more docs below the screenshot e.g. "For more details, see the docs on [Code Annotation](url)"

**Comment by cwickham** [comment]
@jjallaire OK, I think [this](https://deploy-preview-714--mystifying-jepsen-fa4396.netlify.app/docs/blog/posts/2023-04-26-1.3-release/) is probably more in line with your thinking. I also brought in some of the other highlights bullets.

**Comment by jjallaire** [comment]
Yes, that looks fantastic! 

Let's plan on publishing this (+ related tweets) tomorrow at 9 or 10am PST.

**Pull request merged**
