### PR TITLE
Adds example to gallery.yml

### PR DESCRIPTION
**Pull request by emdelponte**
Adds R4PDE book made with Quarto

### CODE REVIEW

**Comment by emdelponte** [comment]
Here is a screenshot of the book.
r4pde_book

**Comment by jjallaire** [comment]
Thanks!

**Comment by emdelponte** [comment]
@jjallaire thank you! The thumb image of the book cover is not showing up. I can't upload it to the right folder.

**Comment by jjallaire** [comment]
Thanks, just remedied!

**Pull request merged**
