### PR TITLE
clarify that Quarto does not use a Jupyter kernel once published

### PR DESCRIPTION
**Pull request by gordonwoodhull**
Confusion arises because the [Jupyter Widgets](https://quarto.org/docs/interactive/widgets/jupyter.html) page mentions interactivity but doesn't clarify that this can only be with JavaScript, not with Python.

This is some minimal suggested wording to fix [quarto-cli/#5834](https://github.com/quarto-dev/quarto-cli/issues/5834)

I think that Jupyter Widgets, unlike HTML Widgets, can expect to be running with access to a running Jupyter kernel. If it's not in the spec it's something that plotly and others have figured out how to do.

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you for taking care of that one!

**Comment by gordonwoodhull** [comment]
Need to add the freeze, will try soon. Thanks @cderv for the heads up!

**Comment by cderv** [comment]
I have fixed on main the dependency problem. We were missing in our PipFile an undirect dependency for this doc. 

You should now be able to update the freezer for this modification in this PR.

**Comment by gordonwoodhull** [comment]
> there is interactivity with JavaScript but not with Python

Technically, this should say "the Jupyter kernel language" rather than Python. I don't know if there are packages which interact with a kernel language other than Python, but I understand Jupyter is language-agnostic so they probably exist.

**Review by cderv — APPROVED** [review]

**Comment by cderv** [comment]
Awesome thanks !

**Comment by gordonwoodhull** [comment]
After seeing Carson’s talk, wondering if two-way binding is in fact possible using Shiny for Python in Quarto.

**Pull request merged**
