### PR TITLE
Add mention of the .class syntax for source code

### PR DESCRIPTION
**Pull request by cderv**
This follows questions on slack and issue on Quarto like https://github.com/quarto-dev/quarto-cli/issues/7073

I believe this is worth documenting in Markdown basis that the long syntax with brackets can be necessary. 

Possibly a callout to explain the different with computation code can be useful 🤔

### CODE REVIEW

**Comment by cderv** [comment]
I can't make the `@sec-` link working ... 😓 I need to look into that.

**Comment by cwickham** [comment]
@cderv This has been sitting a while but I think it is an important addition. Is there anything else you wanted to add? If not, assign me as a reviewer and I'll do a wording review.

Also I think `@sec` syntax only works when sections are numbered, but maybe @cscheid has more input on that.

**Comment by cderv** [comment]
This is ready now.

**Comment by cderv** [comment]
> Is there anything else you wanted to add? If not, assign me as a reviewer and I'll do a wording review.

@cwickham I did not merge as it seems you wanted to review wording.

**Comment by cwickham** [comment]
Yes! I'll make a commit directly as my suggestion is a bit beyond GitHub's "suggestion" comment.

**Pull request merged**
