### PR TITLE
Avoid gt deprecated arguments

### PR DESCRIPTION
**Pull request by olivroy**
Avoid gt deprecated arguments.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Thank you!

**Comment by olivroy** [comment]
Hi! Thanks for merging! the page has not updated https://quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/gt-cars

**Comment by gordonwoodhull** [comment]
Thanks. Yes I realized after merging that the build on this blog post is not automatic due to the example sub-documents.

I’m out for a couple weeks but I’ll rebuild the post when I get back.

**Comment by olivroy** [comment]
Just a reminder! I still see the deprecated arguments https://prerelease.quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/[gt-cars.pdf](https://prerelease.quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/gt-cars.pdf)

**Comment by gordonwoodhull** [comment]
Thanks for the reminder! I deployed the build artifacts in #1458

**Pull request merged**
