### PR TITLE
gha - add imagemagick to the build

### PR DESCRIPTION
**Pull request by cderv**
@gordonwoodhull Let's just add image magick to preview and see if this help you branch building. 

This is how I would install it. If that works ok, we need to add the same step of other relevant workflow. 

FWIW This PR is not against main, but against your branch needing Magick.

### CODE REVIEW

**Comment by cderv** [comment]
It built, but using the workflow from main (🤦 obviously). So we'll test this once you merge in your branch maybe

**Comment by gordonwoodhull** [comment]
After our discussion, I'm not 100% convinced that we want `magick` on main. 

The way I set this up, if the snapshots are there, the script is a no-op. Maybe we want to keep the snapshots checked in, and have a workflow that has `magick` _plus_ all the table libraries, that force-regenerates the snapshots. Then run that weekly or whatever.

**Comment by gordonwoodhull** [comment]
I've copied this branch locally for reference, thank you!

But as we discussed, I think it's the wrong idea and we should have a separate workflow for this. I'll close this and open another issue for discussion.

**Comment by cderv** [comment]
Ok great. Let's do this !

**Pull request closed without merging**
