### PR TITLE
add a note about conditional evaluation of knitr chunks

### PR DESCRIPTION
**Pull request by topepo**
Per chat in slack on 2022-12-05. 

Not sure if my link syntax (`[Knitr options](tools/_chunk-options.md)`) is correct.

### CODE REVIEW

**Comment by cscheid** [comment]
So that file you're linking is an include, and not an HTML output; we should file places where that include is references and link to that instead.

**Comment by allenmanning** [comment]
@cderv Why have all the checks failed?  I wasn't able to open the Netlify logs to check.  It seems that the preview is working.

**Comment by cderv** [comment]
These are just old checks from the commit of this  PR 3545ce26429efaef86c7f913230655aedd6ce8c0 made in Dec. 2022. 

At this time, the netlify connection and preview was not working. I did not modify the checks of the PR - a new commit is needed to trigger. 

The command in comment run a workflow, but does not update the checks status of the PR. (Maybe I can do that using github API 🤔). 

So basically: All our opened old PR will have failed netlify checks.

**Pull request merged**
