### PR TITLE
Add examples of using divs to separate content

### PR DESCRIPTION
**Pull request by cwickham**
Closes https://github.com/quarto-dev/quarto-cli/issues/4600

Preview Changes:
* [Lists](https://deploy-preview-781--mystifying-jepsen-fa4396.netlify.app/docs/authoring/markdown-basics.html#lists)
* [Block Layout](https://deploy-preview-781--mystifying-jepsen-fa4396.netlify.app/docs/authoring/figures.html#block-layout)

### CODE REVIEW

**Comment by mcanouil** [comment]
For the "list" part the output seems off as the code should produce compact list but we can see a spaced list on the right.
image

The "block layout" is great.
Now the tricky question is how to make it discoverable in the search as most users will likely search for "Multiple Columns" which leads only to `:::: {.columns}` solution.

**Comment by mcanouil** [comment]
I would suggest to refactor the markdown basic document to not use the `.    ` code block syntax and use `` ```{.markdown} `` on the left column, and use the exact same markdown outside the code block in the right column.

Advantages:
- output will actually be the one from the code
- code will have the copy button

**Comment by cwickham** [comment]
I agree with the suggestion to use ` ```{.markdown}`. Interestingly, the visual editor is converting it to ` ``` ` automatically for me. Do you see any reason not to use ` ```markdown`, over ` ```{.markdown} `? ` ```markdown` would involve a lot less fighting with the visual editor on my end.

**Comment by mcanouil** [comment]
Actually it's the same as long as it is a code block with the right language.

**Comment by cwickham** [comment]
Thanks for the suggestions @mcanouil. Refactored this page to use ` ```markdown` and made sure the list code matches the list output. I think we can address discoverability with https://github.com/quarto-dev/quarto-cli/issues/6192.

**Pull request merged**
