### PR TITLE
Use a tidier bulleted list for "Learning more" in website-basics.qmd

### PR DESCRIPTION
**Pull request by yyzeng**

### CODE REVIEW

**Review by cderv — APPROVED** [review]

**Comment by cderv** [comment]
Thanks. 

Adding the list seems good, but this will require to do it in all other learning more sections of the website

**Comment by yyzeng** [comment]
> Thanks.
> 
> Adding the list seems good, but this will require to do it in all other learning more sections of the website

As I remember, <https://quarto.org/docs/presentations/revealjs/> etc. have used bulleted lists in "Learning more". 😄

**Comment by cderv** [comment]
Great ! 

Books does not for now: https://quarto.org/docs/books/#learning-more I'll adapt this one.

**Pull request merged**
