### PR TITLE
Quarto executable source code, without executing it

### PR DESCRIPTION
**Pull request by aborruso**
How to add it

### CODE REVIEW

**Comment by jjallaire** [comment]
We have this documented over here already: https://quarto.org/docs/computations/execution-options.html#unexecuted-blocks

Perhaps we should just duplicate that explanation in the spot you are pointing out?

**Comment by aborruso** [comment]
@jjallaire you are right. I had looked for it, but I had not found it.

Because for me this is an authoring matter and not an execution one. 
I was looking for it in the sections that explain how to write content.
I would also put a reference there.

What do you think about it?

Thank you

**Comment by jjallaire** [comment]
Okay, I just pushed a change that includes this documentation in both places so will close the PR.

**Comment by aborruso** [comment]
Thank you very much

**Pull request closed without merging**
