### PR TITLE
add the diaquarto extension

### PR DESCRIPTION
**Pull request by skriptum**
Custom Format for the easy creation of slides using typst and the diatypst package. Similiar to beamer slides in quarto, but faster

### CODE REVIEW

**Comment by cscheid** [comment]
https://github.com/skriptum/diatypst/diaquarto (from your PR) is a broken link. Can you fix that?

**Review by cscheid — COMMENTED** [review]
How about we use https://github.com/skriptum/diatypst/tree/main/diaquarto instead? I think that's what you originally meant?

**Comment by skriptum** [comment]
even better

**Review by cscheid — APPROVED** [review]

**Pull request merged**
