### PR TITLE
add style-text filter

### PR DESCRIPTION
**Pull request by leovan**
add style-text filter

### CODE REVIEW

**Comment by cscheid** [comment]
Can you please redo your PR so that it doesn't reindent all of the document?

**Comment by leovan** [comment]
You mean just add the new extension and keep the indent problems as before?

**Comment by cscheid** [comment]
Yes - it makes a cleaner commit trail. Thanks.

**Comment by leovan** [comment]
OK, I made another PR, see <https://github.com/quarto-dev/quarto-web/pull/1027>.

**Pull request closed without merging**
