### PR TITLE
note on collapse option

### PR DESCRIPTION
**Pull request by sebacea**
this should orientate people like me seachinf for this functionality

### CODE REVIEW

**Comment by cscheid** [comment]
Thanks for the PR. Can you please fix the typo "revels.js" to "Revealjs" instead, which is the terminology we use in the documentation?

**Comment by sebacea** [comment]
Done @cscheid

**Review by cderv — COMMENTED** [review]
Note that our doc currently state the limitation in the last paragraph
https://quarto.org/docs/authoring/callouts.html#format-support

> Also, some features are specific to document using Bootstrap, like collapsible callouts, and won’t work in other documents.

Maybe we could add there that the limitation applies to Revealjs ?

**Pull request merged**
