### PR TITLE
add vistales website to gallery

### PR DESCRIPTION
**Pull request by Vistales**

### CODE REVIEW

**Comment by cscheid** [comment]
Have you considered making the URL from `https://vistales.github.io/Home/_site/` to `https://vistales.github.io/`?  That would be cleaner and closer to how we intend folks to use Quarto.

**Comment by Vistales** [comment]
Yeah, https://vistales.github.io/vistales also works.

**Comment by cscheid** [comment]
Can you change your PR to use that instead?

**Comment by Vistales** [comment]
Sure, done.

**Pull request merged**
