### PR TITLE
docs: add task list example

### PR DESCRIPTION
**Pull request by mcanouil**

### CODE REVIEW

**Review by cderv — APPROVED** [review]
I think we can add it to main website... so PR on main. 

This is note a new 1.5 feature support, right ?

**Comment by mcanouil** [comment]
It's really a missing example in list. Nothing more.

As I don't know what is the main/pre-release workflow exactly, I assumed new content goes to pre-release and main is for "typos".

Is prelease only for new things/featurzs in CLI? Everything else goes into main?

**Comment by cwickham** [comment]
Yup, `prerelease` is primarily for new features. General doc updates and improvements can go to `main`. For PRs merged to `main`, we have a workflow that automatically creates a PR against `prerelease` to keep it updated.

**Comment by mcanouil** [comment]
Done. New target is `main`.

**Pull request merged**
