### PR TITLE
Replace `reactive.Calc` with `reactive.calc`

### PR DESCRIPTION
**Pull request by wch**
In Shiny for Python 0.6.1 (released 2024-12-18), we added lower-case `reactive.calc`, and we just switched our examples to use `reactive.calc` instead of `reactive.Calc`. (Note that the existing `Calc` will continue to work.)

I also updated the recommended version of Shiny on this page from 0.6 to 0.6.1.

This PR also has a number of changes where my editor stripped out trailing whitespace. If that's undesirable, let me know and I can revert them.

### CODE REVIEW

**Comment by wch** [comment]
I also noticed there is a file named [docs/dashboards/_examples/inputs/global-sidebar copy.qmd](https://github.com/quarto-dev/quarto-web/pull/1044/files#diff-32946dbd13f388dc0026ea10944eb92ab7d34696b8c3a8e15118e08c1174dc1b), which I found when I did my search and replace. I don't see where this file is referenced. Is it possible this file was committed by mistake?

**Comment by cscheid** [comment]
lgtm

**Comment by cderv** [comment]
> [global-sidebar copy.qmd](https://github.com/quarto-dev/quarto-web/pull/1044/files#diff-32946dbd13f388dc0026ea10944eb92ab7d34696b8c3a8e15118e08c1174dc1b),

Yes I think this is not needed and the real doc is https://github.com/quarto-dev/quarto-web/blob/6a7ef133ab91716f13200beae1158562d8bb7a3b/docs/dashboards/_examples/shiny-global-sidebar.qmd

**Comment by wch** [comment]
Thanks, I've removed that file.

**Pull request merged**
