### PR TITLE
Update book-crossrefs.qmd

### PR DESCRIPTION
**Pull request by aborruso**
I have added a premise, which I think is useful, on the use of the '-' symbol.

### CODE REVIEW

**Comment by cderv** [comment]
duplicate of #961 ?

**Comment by aborruso** [comment]
> duplicate of #961 ?

With #961 I have extented #960: I added that the `-` is not needed for a custom prefix.

**Comment by cderv** [comment]
#961 contain commit https://github.com/quarto-dev/quarto-web/pull/960/commits/2d72b49e6136afa29ef5129936b32c0f8214d329 which is also in here. 

So if we merge #961 this PR seems irrelevant

**Comment by aborruso** [comment]
> So if we merge https://github.com/quarto-dev/quarto-web/pull/961 this PR seems irrelevant

Yes, I'm sorry. But I wanted to explain what I had done.

Thank you again

**Comment by cderv** [comment]
All good. Just wanted to be sure I got it right on my side and not close while it should not be. Let's focus on #961 now

**Pull request closed without merging**
