### PR TITLE
Update vscode.qmd

### PR DESCRIPTION
**Pull request by ToriOblad**
Added pandas to the pip install statements since plotly express requires pandas to be installed.

### CODE REVIEW

**Comment by cscheid** [comment]
We don't want to add that installation requirement to the instructions; Quarto itself doesn't require Pandas.

**Comment by cscheid** [comment]
> Added pandas to the pip install statements since plotly express requires pandas to be installed.

If that's what we're using, then we should declare the correct dependency from pip, https://pypi.org/project/plotly-express/

**Comment by cderv** [comment]
For context, this is the current error when executing the code without Pandas installed

````python
import plotly.express as px
import plotly.io as pio
gapminder = px.data.gapminder()
gapminder2007 = gapminder.query("year == 2007")
fig = px.scatter(gapminder2007, 
                 x="gdpPercap", y="lifeExp", color="continent", 
                 size="pop", size_max=60,
                 hover_name="country")
fig.show()
````

Error: 
````
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import plotly.express as px
      2 import plotly.io as pio
      3 gapminder = px.data.gapminder()

File ~\.pyenv\pyenv-win\versions\3.12.1\Lib\site-packages\plotly\express\__init__.py:9
      7 pd = optional_imports.get_module("pandas")
      8 if pd is None:
----> 9     raise ImportError(
     10         """\
     11 Plotly express requires pandas to be installed."""
     12     )
     14 from ._imshow import imshow
     15 from ._chart_types import (  # noqa: F401
     16     scatter,
     17     scatter_3d,
   (...)
     50     density_mapbox,
     51 )

ImportError: Plotly express requires pandas to be installed.
````

They make `pandas` optional in plotly, while it was required by previous external package `plotly_express`. 

I'll update this other file and merge

**Pull request merged**
