### PR TITLE
Adding codefocus as plugin

### PR DESCRIPTION
**Pull request by reuning**

### CODE REVIEW

**Comment by jjallaire** [comment]
@cderv Could you review this?

@reuning I tried the linked to demo but didn't see anything happen in the code block for the initial example. Is that all working as expected?

**Comment by reuning** [comment]
Strange. It was working yesterday... Let me double check somethings.

**Comment by reuning** [comment]
All fixed.

**Review by cderv — APPROVED** [review]
Yes this looks good and work well for me. That is a nice extension !

**Pull request merged**
